### ISSUE TITLE
Issue with Item Sets (5 of 6 items displayed)

### ISSUE THREAD

**Issue by andresrw** [dustinblackman/Championify#337] opened 2017-09-13 19:17 UTC
I have been having an issue with my in-game item sets.  Only 5 out of the 6 of the completed Items show up on my in-game shop for each of the item sets. For example, under the "highest win rate" item build path, only 5 of the 6 completed items are displayed.

 I only use the champion.gg item sets.

![bad item set](https://user-images.githubusercontent.com/31935362/30396148-ada2e598-9896-11e7-9329-79736c77fa41.jpg)

**Comment by andresrw** [comment] 2017-09-13 19:20
Also confirmed that this issue exists for the "Most Frequent Used" Champion.gg set

**Comment by dustinblackman** [comment] 2017-09-13 19:57
Which ADC are you playing in the screenshot?

**Comment by andresrw** [comment] 2017-09-13 20:02
Xayah; but it’s an issue with all the champions I play.

**Comment by andresrw** [comment] 2017-09-13 20:09
Hmmm so I tested it with Yasuo and Vi to see if it was role specific. The issue exists with Yasuo, but VI seems to be ok? I mostly ADC/Mid.

![bad item set 2](https://user-images.githubusercontent.com/31935362/30398284-d9ea2dd0-989d-11e7-9d3d-949f83a78abe.jpg)

**Comment by andresrw** [comment] 2017-09-13 20:11
Janna also has the issue 
![bad item set 3](https://user-images.githubusercontent.com/31935362/30398396-349efecc-989e-11e7-985b-600ade13e571.jpg)

**Comment by andresrw** [comment] 2017-09-13 20:12
Also I just noticed sometimes a starter item (such as ancient coin) can be missing.

**Comment by dustinblackman** [comment] 2017-09-13 20:20
Ah. The issue is Ornn. The item missing for example Salvation which is built from Redemption only when Ornn is on your team. This is a dup of https://github.com/dustinblackman/Championify/issues/238, closing.

**Closed** 2017-09-13 20:20 UTC
