### ISSUE TITLE
Can't get Riot Version

### ISSUE THREAD

**Issue by espenodge** [dustinblackman/Championify#229] opened 2016-12-20 21:14 UTC
Hello,
   I'm new with Championify and wanted to give it a try, since the new client update with League doesn't have Item sets any longer. I installed the Windows version of the program (I have Windows 10) and the program says that it has "Found League of Legends!" in my folder directory. The issue I'm having is that when I click the Import button it flashes text saying that it's unable to get my LoL version. And then I get the kitty cat saying not available. 
On the main screen of Championify it says "Item Sets Version: Unknown" & "LoL Version: Loading..."
Every thing else seems to be ok. The version of Championify I'm using is v1.3.8.
I ran the program as Administrator & I allowed the program in my firewall settings. I still get the same issue. I tried to research online to see if someone had a similar issue but doesn't seem anyone has posted about it. Any help with this is greatly appreciated, thank you.

**Comment by deviim** [comment] 2016-12-20 21:28
Having same issue, i've been using championify since it was posted on reddit but i tried updating it yesterday but it said it couldn't get LoL version, i tried unistalling championify/LoL, run as administrator, allowed program in firewall settings nothing seems to work :/

**Comment by iggyvolz** [comment] 2016-12-20 22:22
Same here.  Possibly because of the new client?

The "Item Sets Version" for me is set to 6.22, that last version I successfully updated for.

**Comment by iggyvolz** [comment] 2016-12-20 22:23
Looks like a duplicate of #227

**Comment by dustinblackman** [comment] 2016-12-20 22:59
Dup. https://github.com/dustinblackman/Championify/issues/227

**Closed by dustinblackman** 2016-12-20 22:59 UTC
